### ISSUE TITLE
To improve the spectacular color?

### ISSUE THREAD

**Issue by wuweiran** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#64]
https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/eae09e0eef0ecaa680e27a03c7766413a4852236/source/chapter1/main.cpp#L558C5-L584C6

    if ( NdotL > 1e-5 ) {
        // ...
    } else {
        frag_color = vec4( base_colour.rgb * 0.1, base_colour.a );
    }

Why is the else branch specially handled? That makes the model look awful.

**Comment by theWatchmen** [comment]
The idea is to fake an ambient colour to avoid having the non-lit side of the mesh to be completely black. Probably not the best looking result, but we improve the lighting model later in the book :)

**Comment by wuweiran** [comment]
I think it'll be OK to use default lighting model here in Chapter 1. Otherwise, some learners (like me) may think they did something wrong in env setup.

**Comment by theWatchmen** [comment]
Using an ambient term is pretty standard practice when using such basic lighting model. Otherwise anything hidden from the light would be black. I agree maybe we should have explained it better either in the chapter or in the code, however the assumption is that people reading this book are already familiar with some of the basic graphics concepts and we can skip over some of the details.
